<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PPJK</name>
   <tag></tag>
   <elementGuidId>45bcbea5-8963-4121-88f9-53cad406df67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/aside/div/div[1]/nav/ul/li[4]/ul/li[19]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a87b4b0e-a3bc-4c5d-86a0-6b7712200b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-dark</value>
      <webElementGuid>ccebcf3f-a170-4b42-817b-63a20ce96e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dummy.oaktree.id/admin/master_ppjk</value>
      <webElementGuid>2bc2892d-90c8-43d5-a0a1-0ba742dd8fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>608cc94c-3ff0-4de0-987a-be15b314118f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											
												
											
											PPJK</value>
      <webElementGuid>c8fc3815-1c1e-4dc1-a78d-ebbcbe85f6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarnav&quot;)/li[@class=&quot;active&quot;]/ul[@class=&quot;collapse in&quot;]/li[@class=&quot;pt-0&quot;]/a[@class=&quot;waves-effect waves-dark&quot;]</value>
      <webElementGuid>fad7276c-b3e1-437d-88a0-298dbf13eb68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarnav']/li[3]/ul/li[19]/a</value>
      <webElementGuid>de1f9fd1-4ef8-4036-95b8-2f8a6a8d0e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[1]/following::a[1]</value>
      <webElementGuid>bdee93ed-8fa8-4a23-bdc5-365a14f8e7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorized'])[1]/following::a[2]</value>
      <webElementGuid>cb5b74dd-b667-4ff0-b22c-d103bf2bd324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Tax'])[1]/preceding::a[1]</value>
      <webElementGuid>b251c13f-ef99-40cf-b654-8444a7d2f51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dummy.oaktree.id/admin/master_ppjk')]</value>
      <webElementGuid>313ed686-f0b8-499b-b80c-d2c990d1c71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]/a</value>
      <webElementGuid>e999975b-3419-4c73-a1e0-6f6f9f2e9f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
