<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_date - Copy</name>
   <tag></tag>
   <elementGuidId>b9006e6a-3d18-4f92-ab6b-d590835c62f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div[3]/div/div/div/div/div/div/div/div[1]/div[7]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00ad7ada-7639-4f0b-8b4a-248b78577b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>3d07fc38-cb42-46eb-a0d7-e055118bf17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1341762a-8346-4a00-9f29-5862ea310c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1747ed34-d147-4c21-b21a-7721ffb2bedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Year</value>
      <webElementGuid>8c23dc30-8a2c-44a6-91db-24739649ff35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-input</value>
      <webElementGuid>f10df061-833d-4c6b-bd71-7cbf4db21624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card new-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;velmld-parent&quot;]/div[@class=&quot;row mb-3&quot;]/div[6]/div[@class=&quot;mx-datepicker&quot;]/div[@class=&quot;mx-input-wrapper&quot;]/input[@class=&quot;mx-input&quot;]</value>
      <webElementGuid>becdf9b6-d22a-4189-b44c-a4191517dff3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
