<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_month</name>
   <tag></tag>
   <elementGuidId>ce402450-b696-4149-a6bb-bcf2244e0671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom-tags']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custom-tags</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>907764c0-6ccb-48f2-84a8-4ae1f815df3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-tags</value>
      <webElementGuid>96ae44a1-9622-4efc-bc2c-f8c8f28a8c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-tags</value>
      <webElementGuid>6ac5d325-7264-43ea-867d-ec6ef6d6afb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>month × </value>
      <webElementGuid>575c9853-f7ad-4195-bfb1-4e6e7f9bf1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-tags&quot;)</value>
      <webElementGuid>56fd9265-2257-4bdd-9eee-e86bad04d7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='custom-tags']</value>
      <webElementGuid>7c158e06-e5c0-4961-a19c-969481dad56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[4]/div[3]/div/div</value>
      <webElementGuid>7e65b7f9-8ec7-4a5c-9689-71a808a4f1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence'])[2]/following::div[7]</value>
      <webElementGuid>5f876534-7e10-4e03-ae45-fc0ae0db629d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::div[7]</value>
      <webElementGuid>3a8bfa86-35ff-4930-9342-d78bf9c69d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add sequence component for auto numbering'])[1]/preceding::div[2]</value>
      <webElementGuid>7e5e0352-9967-47c1-a17e-0968191fa001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div</value>
      <webElementGuid>0785d2ca-e9b1-4d98-a94e-fae20d8bdb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'custom-tags' and (text() = 'month × ' or . = 'month × ')]</value>
      <webElementGuid>84885161-5b55-432f-a013-796b4c1804c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
