<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Month_custom-tags</name>
   <tag></tag>
   <elementGuidId>37d4aac6-eb34-465e-8dc8-0d84b4acb917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom-tags']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custom-tags</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>682d1238-9ce1-477d-9d64-5d89ee25a88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-tags</value>
      <webElementGuid>51b4f2af-82de-4af2-a5d8-6d946b598320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-tags</value>
      <webElementGuid>06966b53-b450-4797-a626-6430fab6d47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-tags&quot;)</value>
      <webElementGuid>a1af270e-177a-4994-86b5-0d739c3cff07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='custom-tags']</value>
      <webElementGuid>519841cd-cd48-4367-8e23-9682e4700649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[4]/div[3]/div/div</value>
      <webElementGuid>6610ca6b-e295-41f7-9926-efd41c98d71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div</value>
      <webElementGuid>83640a74-5e9c-4191-9801-d81e0169f415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'custom-tags']</value>
      <webElementGuid>412ae135-3fea-4197-b63d-8ae5c79b3797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
