<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_please select sequence component for au_26c8a7</name>
   <tag></tag>
   <elementGuidId>c5bd266d-207b-4f66-8dea-ac3043122671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='warning-message']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>818b8a51-528c-49bb-9590-b2f01b9480d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger</value>
      <webElementGuid>ab180de6-d926-4686-9b42-3d4e81749777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>please select sequence component for auto numbering</value>
      <webElementGuid>020a185e-bde9-4188-9d72-f9717f86045b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warning-message&quot;)/div[@class=&quot;alert alert-danger&quot;]</value>
      <webElementGuid>1fadd161-21d6-4e5e-a848-2fb4f7f30f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='warning-message']/div</value>
      <webElementGuid>6bc7c113-5d97-494c-b292-f7656e884aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence'])[2]/following::div[11]</value>
      <webElementGuid>50c869e9-2e1f-46cb-ac3f-66e984072e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numbering Example'])[1]/preceding::div[1]</value>
      <webElementGuid>db2a7c56-5573-4ce9-9aa8-7f839c372130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='please select sequence component for auto numbering']/parent::*</value>
      <webElementGuid>d9779314-a8b2-42e8-9c27-a6cf945c7cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>242ecb85-5227-479d-8f54-1ac102ab3ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'please select sequence component for auto numbering' or . = 'please select sequence component for auto numbering')]</value>
      <webElementGuid>3bfec9c9-9452-44bc-a9d3-1ad06abab833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
