<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Welcome to Oaktree_eye-icon</name>
   <tag></tag>
   <elementGuidId>06cec0f3-edc3-4564-8bb4-6e7f35d43f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='eye-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eye-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c7bbe145-e9a7-46de-9557-9e4f8b30051b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye-slash mr-3</value>
      <webElementGuid>b1ed54d5-6b15-4cd0-9c3d-9763ffc55d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eye-icon</value>
      <webElementGuid>73fc74af-13fd-4bdb-b8fe-597baf7aaebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>035127e3-cc0b-4b62-8095-6340f854852a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eye-icon&quot;)</value>
      <webElementGuid>11b17a82-49c4-4a21-97db-b6a2830aae21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='eye-icon']</value>
      <webElementGuid>faf7768e-5b02-4aac-bacd-2f49804bc58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_hide_password']/span/a/i</value>
      <webElementGuid>250dd80c-91ab-4671-aeee-b3fe06646259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>a3018808-9121-455b-b241-e717074c5aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'eye-icon']</value>
      <webElementGuid>966a1261-e30c-45e4-bcf0-fb6a5a90700d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
