<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cash in Bank - Surabaya</name>
   <tag></tag>
   <elementGuidId>df828d16-b166-478a-9a4d-8356fa67f057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-id_aol-bh-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc4fd299-f0f2-4590-b165-f3ba66aced81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>49ba0c13-17e9-43bd-89ee-78127adb8145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-id_aol-bh-container</value>
      <webElementGuid>dec835b8-4faa-476f-950e-b36bbb87e7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cash in Bank - Surabaya</value>
      <webElementGuid>0dde5430-7ffa-4f7b-bf39-064f283b7c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cash in Bank - Surabaya</value>
      <webElementGuid>48065f5d-1789-46ab-8e39-b3d1a9e490a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-id_aol-bh-container&quot;)</value>
      <webElementGuid>4517e846-884c-42e0-a7cf-efce82dde231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-id_aol-bh-container']</value>
      <webElementGuid>42c10588-51cd-43e0-9306-b6802f042996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[16]/div/span/span/span/span</value>
      <webElementGuid>b8f3ab73-b446-4424-b334-1c8850f93811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accurate Autonumber ID'])[1]/following::span[4]</value>
      <webElementGuid>1ebc5635-1e79-4a12-b0be-b46ff9ba2881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::span[4]</value>
      <webElementGuid>6dde54c0-6d3f-4191-8927-74bc4d25d8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This autonumber for copy jobfile'])[1]/preceding::span[3]</value>
      <webElementGuid>7daf4179-af81-4eee-83b3-e9499a82fdd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internal Autonumber'])[1]/preceding::span[3]</value>
      <webElementGuid>57220214-370b-46e2-8b84-4f239fcf6262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/span/span/span/span</value>
      <webElementGuid>1037888f-8dc9-4ffe-a808-a88134e34226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-id_aol-bh-container' and @title = 'Cash in Bank - Surabaya' and (text() = 'Cash in Bank - Surabaya' or . = 'Cash in Bank - Surabaya')]</value>
      <webElementGuid>892b849a-b130-4dea-bd8a-be0fec9b03b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
