<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Month</name>
   <tag></tag>
   <elementGuidId>af14a3ad-b3eb-44b2-aa65-23949ec21455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-component-xe-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-component-xe-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bddd0a4e-f718-4a17-aedb-a3d75a5beff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7bd7a2d3-2ffc-4ff1-96e7-3c61e0d0c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-component-xe-container</value>
      <webElementGuid>654229ec-fae6-49f4-a06c-540f09729e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>2a1dd35c-8f56-47e3-84aa-263bc7a384ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>74704efa-49ae-459d-9ee1-aedaa580cddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-component-xe-container&quot;)</value>
      <webElementGuid>be9c6096-5197-4653-9575-771e86f5d7b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-component-xe-container']</value>
      <webElementGuid>45b1b51f-de75-40d7-964d-470a24dd178b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[4]/div/div/span/span/span/span</value>
      <webElementGuid>983012ac-f3cf-4244-8b79-6c5a60f1a7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::span[4]</value>
      <webElementGuid>797059f5-162c-4ce1-973a-e10b8523089c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add sequence component for auto numbering'])[1]/preceding::span[4]</value>
      <webElementGuid>dbb4aed9-44bc-41be-8319-79a613eb614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/span/span/span</value>
      <webElementGuid>c90b9ff2-4a47-48cf-99c8-fdae0ffa7f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-component-xe-container' and @title = 'Month' and (text() = 'Month' or . = 'Month')]</value>
      <webElementGuid>d6e200fa-00b2-4c68-a8e0-248cc2af9d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
