<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Job Order Loading_edit</name>
   <tag></tag>
   <elementGuidId>11e8998f-e6c9-412f-8e87-cf6987439e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='edit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8215001e-3131-458d-9838-a6cbdd834fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dummy.oaktree.id/assets/admin/images/icon-delete.svg</value>
      <webElementGuid>879ec3f2-b0d8-488c-84cd-7cee771c287a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>73cef0d4-7c90-49c4-b546-7e81e728cc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>68242dd4-93e0-467e-968a-722cfc5a3a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12d3ea9f-fcb2-4a82-a247-2828f81a81ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/button[@class=&quot;btn btn-action&quot;]/img[@id=&quot;edit&quot;]</value>
      <webElementGuid>0f4d018e-9b9b-4ce0-aaf1-99d6096cf114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='edit'])[3]</value>
      <webElementGuid>a980c9a3-9194-41fd-8686-9400ecaca4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr/td[6]/button[3]/img</value>
      <webElementGuid>e0610f98-ffbb-4a5c-a829-f5c185fad6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dummy.oaktree.id/assets/admin/images/icon-delete.svg')]</value>
      <webElementGuid>12e81b8a-b856-4f15-9ebf-b74e8c12660e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/img</value>
      <webElementGuid>3d71a86e-8bc6-40f4-abd0-dd432d8aa5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dummy.oaktree.id/assets/admin/images/icon-delete.svg' and @id = 'edit']</value>
      <webElementGuid>9f4f3a25-4da8-48ab-8067-19c41ae94dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
