<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current Counter_input_sequence</name>
   <tag></tag>
   <elementGuidId>a7bd36e5-5dd3-409a-88e8-2765b5c214b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-sequence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-sequence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b10c74bb-552e-4f61-8705-ba08fa38aae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>af93bf05-8331-4975-8415-dca7c064b621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c22c52e-19cc-44e1-a761-5c484892829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-sequence</value>
      <webElementGuid>062ce511-f962-4a71-8058-10912f2e03a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_sequence</value>
      <webElementGuid>77d9a519-11f2-4f05-8296-a228b7278335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Current Counter</value>
      <webElementGuid>7c60ae40-026b-4e88-b9d2-5f4885094937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-sequence&quot;)</value>
      <webElementGuid>8e38f387-9057-4aba-b279-193e8f8b508f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-sequence']</value>
      <webElementGuid>7b4b50fc-53f9-48fc-80ca-ecf93b4ca55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-counter-period']/div[2]/div/input</value>
      <webElementGuid>6b32637d-357f-445f-a86b-6606b31ce945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>3dd7c7e0-6e5e-4fb3-8835-c06e8eaf473e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'input-sequence' and @name = 'input_sequence' and @placeholder = 'Current Counter']</value>
      <webElementGuid>f19e02b6-3787-4dea-8390-97bd6316f8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
