<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Not ResetDailyMonthlyYearly</name>
   <tag></tag>
   <elementGuidId>c97784d7-b0d5-41ed-bbbe-d4a6aacbe3e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='reset_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reset_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f8e9609-956e-4830-be05-d3d7bd619779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>efc8dbad-bfc5-4d5c-8d52-450afdf5a840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reset_type</value>
      <webElementGuid>d8402967-0759-40e1-a551-41911db5efd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reset_type</value>
      <webElementGuid>71b34be6-a5e1-4dcb-8be9-b3b1dd3b516f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Not Reset
								Daily
								Monthly
								Yearly
							</value>
      <webElementGuid>d058a77d-9ac3-41f2-9a70-efc50554fcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reset_type&quot;)</value>
      <webElementGuid>fe1d0eea-b60e-4c5c-960f-1fdb02e490e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='reset_type']</value>
      <webElementGuid>e60bd208-a46d-4244-963d-27a8d7b23b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[8]/div/select</value>
      <webElementGuid>0eb8c095-7692-47f4-81de-5e0e9abe4092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Type'])[1]/following::select[1]</value>
      <webElementGuid>58bfd21c-50f0-4e2d-8165-56f0891b84a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::select[1]</value>
      <webElementGuid>de51f382-b7e6-475f-92d7-ba4ee7a795d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>8e1291c4-1cbd-4266-bb1e-66503d7d922a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>7c36744b-cee5-4073-8df4-ded432916e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'reset_type' and @id = 'reset_type' and (text() = '
								Not Reset
								Daily
								Monthly
								Yearly
							' or . = '
								Not Reset
								Daily
								Monthly
								Yearly
							')]</value>
      <webElementGuid>3d588df0-1c77-4da3-b0ff-4d841ecb64fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
