<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Leads_far fa-calendar-alt</name>
   <tag></tag>
   <elementGuidId>93a768b7-96f9-4fb8-9eee-682aabf20479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[3]/div/div/div/div/div/div/div/div[3]/div/div/table/tbody/tr/td[9]/div/a[4]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.far.fa-calendar-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-calendar-alt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card new-card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;velmld-parent&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;table table-centered table-striped&quot;]/div[@class=&quot;vuetable-body-wrapper&quot;]/table[@class=&quot;vuetable ui blue selectable unstackable celled table fixed&quot;]/tbody[@class=&quot;vuetable-body&quot;]/tr[1]/td[@class=&quot;vuetable-slot text-center&quot;]/div[@class=&quot;table-button-container&quot;]/a[@class=&quot;action-icon text-white mr-1 btn btn-sm btn-secondary&quot;]/i[@class=&quot;far fa-calendar-alt&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div/div/div/div/div/div[3]/div/div/table/tbody/tr/td[6]/div/a[3]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
   </webElementXpaths>
</WebElementEntity>
