<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>5e6ca966-a780-4c76-a836-f614a0b90d91</elementGuidId>
   <imagePath>//*[@id=&quot;edit&quot;]</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-action.mr-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;table&quot;]/tbody/tr[1]/td[5]/button[1]
</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>//*[@id=&quot;edit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
