<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel_1_Edit</name>
   <tag></tag>
   <elementGuidId>bc51d4df-2fdb-421b-8b26-2f61c9fdaa73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cancel</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'cancel']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[7]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>beb26300-aadd-405a-9c66-060e125f9bd3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
