<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JKT-F2110.0402-O</name>
   <tag></tag>
   <elementGuidId>d5a9bac2-6a84-4d4f-89c5-41ee9954f6ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[1]/div/div/div/table/tbody[1]/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;View Detail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05f772a0-9b74-4cfa-b74b-810bd62461b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>5c9afddc-d4e1-4f1d-93ef-b7afadc652cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>view_jobfile(5908)</value>
      <webElementGuid>59da5637-3ab9-434d-94bb-3edaabeaf2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View Detail</value>
      <webElementGuid>2df4d936-7923-4788-ad70-6c054e4ca3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JKT-F/21/10.0402-O</value>
      <webElementGuid>b0496ac1-a1cf-4364-8975-c7ce0a558bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/a[1]</value>
      <webElementGuid>a9de2c6e-8bc0-443e-a117-86582dc9e0a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='view_jobfile(5908)']</value>
      <webElementGuid>a306acd1-fb6b-4fd6-ba47-ffacffe2655a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr/td[3]/a</value>
      <webElementGuid>b18c9ed5-a326-4703-b4d4-db95297bf94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JKT-F/21/10.0402-O')]</value>
      <webElementGuid>df158aa2-3d2e-4d1a-b315-51a30a678b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B 9985 UIX'])[1]/following::a[1]</value>
      <webElementGuid>dc467108-f6c1-470c-b188-c66a0d438eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profit'])[1]/following::a[1]</value>
      <webElementGuid>c6d88848-7afc-46e8-a2e0-c9abb33f7ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT PUIM'])[1]/preceding::a[1]</value>
      <webElementGuid>7ec0d5eb-71c9-4c0d-8b03-f1caec99b5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 0.00'])[1]/preceding::a[2]</value>
      <webElementGuid>1fdf51ea-2486-4bd7-837d-5f8ee64f1f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JKT-F/21/10.0402-O']/parent::*</value>
      <webElementGuid>1ccbc6ad-2b69-4fc1-80cc-055f22bf6d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[12]</value>
      <webElementGuid>a2e20db5-2232-4c82-b77a-0c030fff4d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>aaaa0db3-de45-4a74-b85d-7049d30cb034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @title = 'View Detail' and (text() = 'JKT-F/21/10.0402-O' or . = 'JKT-F/21/10.0402-O')]</value>
      <webElementGuid>ba6b79cf-c337-467c-a2b2-6226c1694a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
