<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_JKT-F2110.0402-O</name>
   <tag></tag>
   <elementGuidId>2ff0c87b-5c29-4edc-9a44-1a3b498e602c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobfile-no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='jobfile-no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>6f964ebd-5fe1-4dc0-b092-598f6ead1bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-b-0 uppercase font-weight-500</value>
      <webElementGuid>af039a98-ccd8-42a9-84cf-9491b3f94cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobfile-no</value>
      <webElementGuid>c3be942c-59c7-4541-9639-7f0b613405c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JKT-F/21/10.0402-O</value>
      <webElementGuid>b0bae292-a536-4e5a-8d6c-ba28d3176d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobfile-no&quot;)</value>
      <webElementGuid>ffba6b69-5818-4132-a1b2-10e01ab3fccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='jobfile-no']</value>
      <webElementGuid>1aad5d9a-a504-49af-b72d-809663545e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-jobfile']/div/div/div/div/div/div/h4</value>
      <webElementGuid>94223d83-d0f8-4300-8659-67f452920dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::h4[1]</value>
      <webElementGuid>da8bde4e-3b50-4414-b8cb-f33b7b1d64ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::h4[1]</value>
      <webElementGuid>db30e8c4-6554-4020-b478-7504315642e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[3]/preceding::h4[1]</value>
      <webElementGuid>a5897322-4733-4827-97b3-77280e992d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>c574cecf-b1fe-4260-a88e-74b3d1026d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'jobfile-no' and (text() = 'JKT-F/21/10.0402-O' or . = 'JKT-F/21/10.0402-O')]</value>
      <webElementGuid>7e264be0-c6d8-45cc-9acc-651de2a2544a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
