<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to Oaktree_email_user</name>
   <tag></tag>
   <elementGuidId>d6ee1df8-d6f6-4e14-bcdf-f93e2769b1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f4a7f92-ac93-4ebb-af79-e913ab6d85a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-left-0</value>
      <webElementGuid>b9eb984e-792b-42e2-95ed-77fd94737c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bedfa228-6ea8-4da8-bd34-80dbe56233c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_user</value>
      <webElementGuid>4c959a82-5adf-4f3d-9199-d68c2d2288c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_user</value>
      <webElementGuid>caf359a2-eb23-4525-84df-4a90189bf019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>2beb738f-c1ac-4358-9be9-cfeeed7168fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_user&quot;)</value>
      <webElementGuid>d904df09-7be3-4182-a2ad-4b657e92126a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_user']</value>
      <webElementGuid>ba890b79-6962-4054-9005-68ddd80f46d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div/input</value>
      <webElementGuid>83fa700f-d69f-43db-a93d-2fed7faad92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a90aa027-c8bf-4f6f-9def-b2459db58266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_user' and @id = 'email_user' and @placeholder = 'Email']</value>
      <webElementGuid>5f11abb9-3303-42db-a671-f3e3a9f6e3c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
