<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_start_date</name>
   <tag></tag>
   <elementGuidId>4aae5101-eeb3-4a9b-808e-cd6399414827</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='start_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0046ed5e-156c-46b6-b990-43ba4f1a0607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5025dd13-ac5d-4bc1-ae43-14c48c44c95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start_date</value>
      <webElementGuid>2af1e772-7dd7-42d6-82c8-82a7a7dbbbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>fad233c4-cb50-4e8d-af20-e577a479fd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start_date</value>
      <webElementGuid>9e74dd84-e84a-4b78-8b54-ae5ff7bc0708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start Date</value>
      <webElementGuid>e4dfaa61-0e5f-4919-8835-3be0d84e3645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start_date&quot;)</value>
      <webElementGuid>90705265-fd6e-4019-9215-0433a27e34dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='start_date']</value>
      <webElementGuid>153d1555-6d03-49e5-bd15-4f5ba2960e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start-date-field']/div/input</value>
      <webElementGuid>0022e247-9e54-4b40-b6fd-536a5844aaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>d79f74cb-d82d-480f-be09-4d4c2951c267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'start_date' and @id = 'start_date' and @placeholder = 'Start Date']</value>
      <webElementGuid>d27bb94b-d83d-4d43-9b35-7c9f0dcca4e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
