<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Custom</name>
   <tag></tag>
   <elementGuidId>b44a582a-138e-484a-bddb-39543b9f64e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-range_type-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-range_type-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b79a05a-cf54-469f-b6c4-07cd920d1c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1f104fdf-baf7-480d-b5b9-fff7ce3ed277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-range_type-container</value>
      <webElementGuid>8e315419-33ff-4639-b608-6948416c40bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Custom</value>
      <webElementGuid>b1318fe9-d155-402f-9e77-d817e165c964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Custom</value>
      <webElementGuid>2c86c27e-49c9-43ac-9d15-25e4cc5a3bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-range_type-container&quot;)</value>
      <webElementGuid>0d174740-8e9b-4204-b622-cd79b0e84d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-range_type-container']</value>
      <webElementGuid>125c8898-5d9b-4b83-a055-4870693f4302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-filter']/div/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>d8e1238f-ccf9-4e57-83a7-87980086be94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range Type'])[1]/following::span[4]</value>
      <webElementGuid>5d2a0a29-2ffc-47cc-9d13-8861109db508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistic'])[5]/following::span[6]</value>
      <webElementGuid>4f78df6d-a4f0-4a5b-95ce-5a6ebc27d533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::span[3]</value>
      <webElementGuid>50eafb84-2dab-4ef8-a9b0-e838e0ab34ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/preceding::span[3]</value>
      <webElementGuid>bbb46248-b27f-4004-b0b6-117df99186df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/span/span/span</value>
      <webElementGuid>da0084ef-daab-4375-9668-57d2b204a21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-range_type-container' and @title = 'Custom' and (text() = 'Custom' or . = 'Custom')]</value>
      <webElementGuid>a6649142-e8af-4eec-84d1-7d66f1ce7114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
