<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logistic</name>
   <tag></tag>
   <elementGuidId>03d1bedb-911c-470c-88bc-f653c238182a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--bootstrap.select2-container--below.select2-container--open > span.selection > span.select2-selection.select2-selection--single > #select2-type_jobfile-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='select2-type_jobfile-container'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4451f13-4aa5-4b4c-aa67-fbdc680211c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>61e62bdc-e575-4fa5-8b2d-dd975d2f3b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-type_jobfile-container</value>
      <webElementGuid>3128884f-2672-4ce8-b7ee-69c1be8d4080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logistic</value>
      <webElementGuid>07e9de9c-a1a9-463a-b5ff-d1228887e5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logistic</value>
      <webElementGuid>333bb72b-1316-461d-8935-acb72c44664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-filter&quot;)/div[@class=&quot;form-body row&quot;]/div[@class=&quot;col-md-10 pr-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 pr-2&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap select2-container--below select2-container--open&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]/span[@id=&quot;select2-type_jobfile-container&quot;]</value>
      <webElementGuid>82cd5fbf-d555-41f5-9da4-438ab83bbf36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='select2-type_jobfile-container'])[2]</value>
      <webElementGuid>491bdf7e-ffcc-4252-bb1a-e6402f4bf6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-filter']/div/div/div/div[3]/span/span/span/span</value>
      <webElementGuid>0c6b8fc7-d9de-41e4-abf1-1a637b230ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Type'])[1]/following::span[4]</value>
      <webElementGuid>c101cc67-d36e-4d47-9c78-8ce3e5f2c81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[3]/following::span[8]</value>
      <webElementGuid>3d0b5f4d-1d46-4df9-a2ca-8b960faaa047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range Type'])[1]/preceding::span[3]</value>
      <webElementGuid>e07915b0-3c50-4493-8bae-68a193afe73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[2]/preceding::span[3]</value>
      <webElementGuid>6fa1ca21-e775-48bc-8285-0a6357ea517c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>2c879693-b46a-40df-8a6c-eccf0ff93d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-type_jobfile-container' and @title = 'Logistic' and (text() = 'Logistic' or . = 'Logistic')]</value>
      <webElementGuid>a0cc2a5e-1159-4a06-b45d-c53e4707f8db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
