<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>b77f7f05-3cf8-4816-975e-3bd0b31c9d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-type_jobfile-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-type_jobfile-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c5f36672-3f13-48f8-a377-0796100d56ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>906244df-ee97-4390-a285-2d579da56b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-type_jobfile-container</value>
      <webElementGuid>a15e5bac-b576-4e3e-bb18-7ec844a04efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>0bf40a14-84ea-4822-87bc-24ee8dbbff00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>8db22293-bd0f-4af0-90de-88f0594e3970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-filter&quot;)/div[@class=&quot;form-body row&quot;]/div[@class=&quot;col-md-10 pr-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 pr-2&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap select2-container--below select2-container--open&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]/span[@id=&quot;select2-type_jobfile-container&quot;]</value>
      <webElementGuid>24105476-3574-4368-9dd8-8746c8fa2a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-type_jobfile-container']</value>
      <webElementGuid>fb9f6958-a391-4f8a-a561-e7d36bb129b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-filter']/div/div/div/div/span/span/span/span</value>
      <webElementGuid>4e7df3e0-31ca-426b-affb-e44cbdfbaffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobfile Type'])[1]/following::span[4]</value>
      <webElementGuid>a2fe13d6-a5a5-443f-a01b-32d04fa1a1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Job Order'])[1]/following::span[4]</value>
      <webElementGuid>5185b189-855c-4f7d-9beb-b160c50e626d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[3]/preceding::span[3]</value>
      <webElementGuid>915b4629-db8a-44f4-94b5-5e74794fab00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Type'])[1]/preceding::span[7]</value>
      <webElementGuid>3e93b429-158d-43b3-b5ef-d58dcacd8998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>d821e33e-ba76-4807-a6a0-9a23bfb86178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-type_jobfile-container' and @title = 'All' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>8142663e-282a-45f7-95b5-59d49f339b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
